export { Navbar } from './layout/Navbar/Navbar'
export { Parimid } from './quiz/Parimid/Parimid'
export { PlayQuiz } from './quiz/PlayQuiz/PlayQuiz'
export { Timer } from './quiz/Timer/Timer'
export { ResultCard } from './result/ResultCard'
